### ISSUE TITLE
Crash on stopping server

### ISSUE THREAD

**Issue by Chaos99** [eltorio/RtkGps#10]
Both when using the ''options' soft button as well as the menu, stopping the service causes the app to crash.

Package version: 23
Package version name: 1.0 alpha 23

java.lang.NullPointerException

Source file: RtkNaviService.java
Source class: gpsplus.rtkgps.RtkNaviService
Line number: 295

Stack trace (abbriviated):
java.lang.Runtime Exception: Unable to start service
gpsplus.rtkgps.RtkNaviService@2e747f1 with Intent
{ act=gpsplus.rtkgps.RtkNaviService.STOP cmp=gpsplus.rtkgps/.RtkNaviService }:
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean gpsplus.rtkgps.DemoModeLocation.isInDemoMode()' on a null object reference 
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3320)
at android.app.ActivityThread.access$2200(ActivityThread.java:177)
at android.app.ActivityThread.$H.handleMessage(ActivityThread.java:1549)
at android.os.Handler.dispatchMessage(Handler.java:102)
at [...]
Caused by:
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean gpsplus.rtkgps.DemoModeLocation.isInDemoMode()' on a null object reference 
at gpsplus.rtkgps.RtkNaviService.processStop(RtkNaviService.java:295)
at gpsplus.rtkgps.RtkNaviService.onStartCommand(RtkNaviService.java:153)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3303)
[...]

**Comment by felixk0815** [comment]
Same here, in my case it "just" crashes when the Mock-Provider is enabled. In my case it also crashes, when the mock provider tries to overwrite the systems Gps location and I need the mock provider urgently. Currently I try to finally build the project on my own and start debugging, but thats the hardest part until now.

**Comment by gto234** [comment]
You have to enable the mock location in developer options of your phone in order to work with mock location in rtkgps+ otherwise it crashes.

**Comment by felixk0815** [comment]
I forgot to add the fact that this was enabled. Android 6.01 is currently the OS of my private Smartphone. I tested it with another device with 4.4.2 and it worked. But thanks for replying.

**Comment by Chaos99** [comment]
My Problem also stopped after disabling the mock provider. I'm on a non-rooted phone, and it was not enabled in the developer options, so this shouldn't work anyway. but seems like the app does not check if it's possible to set the mock provider or not.
